version: '3.4'

services:
  webstore:
    image: ${DOCKER_REGISTRY-}webstore
    build:
      context: .
      dockerfile: WebStore/Dockerfile
    depends_on:
        - db
    
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=MyStrong@Passw0rd
